### ISSUE TITLE
Button sprite sheet

### ISSUE THREAD

**Issue by elzasarahjohnson** [elzasarahjohnson/Toddler-Trouble#7]
Buttons for:

PLAY
HOW TO PLAY
OPTIONS
BACK
RESTART / PLAY AGAIN
MAIN MENU

**Comment by sabishiangel** [comment]
~~PLAY~~
~~HOW TO PLAY~~
~~OPTIONS~~
BACK
RESTART / PLAY AGAIN
MAIN MENU
